# 应用服务 WEB 访问端口
server.port: 9092


# DataSource config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/app_mgmt?useUnicode=true&characterEncoding=utf-8
    username: xxx
    password: xxx
  sql:
    init:
      schema-locations: classpath:sql/app_mgmt_init_table.sql
      data-locations: classpath:sql/app_mgmt_init_data.sql


mybatis-plus:
  mapper-locations: classpath:mappers/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# 下面这些内容是为了让MyBatis映射
##指定Mybatis的Mapper文件
#mybatis.mapper-locations=classpath:mappers/*xml
##指定Mybatis的实体目录
#mybatis.type-aliases-package=com.rj.appmgr.server.mybatis.entity

#logging:
#  level:


#    com.rj.appmgr.server:debug